require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'V2exPlus' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'V2exPlusTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'V2exPlus-tvOS' do
  # Pods for V2exPlus-tvOS

  target 'V2exPlus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable these next few lines.
use_flipper!({ 'Flipper' => '0.127.0', 'Flipper-Folly' => '2.6.7', })
  
 post_install do |installer|
    flipper_post_install(installer)
    react_native_post_install(installer)
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
          end
      end
  end
